import { StyleSheet } from 'react-native';
import { theme } from '../theme';
import { CELL_W, HOUR_HEIGHT } from './constants';

/**
 * Lesson Diary — extracted stylesheet.
 * Sized constants come from `./constants`.
 */
export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: theme.colors.background },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 12 },
  iconBtn: { padding: 8, borderRadius: 8 },
  title: { ...theme.font.h2 },
  toggleRow: { flexDirection: 'row', justifyContent: 'center', gap: 8, paddingBottom: 4 },
  toggleBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: theme.colors.primary,
    backgroundColor: theme.colors.surface,
  },
  toggleBtnActive: { backgroundColor: theme.colors.primary, borderColor: theme.colors.primary },
  toggleText: { color: theme.colors.primary, fontWeight: '700', fontSize: 13 },
  toggleTextActive: { color: '#fff' },
  weekNav: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 16, paddingVertical: 8 },
  weekArrow: { padding: 8, borderRadius: 8, backgroundColor: theme.colors.primaryLight },
  weekLabel: { ...theme.font.h3 },
  todayHint: { fontSize: 11, color: theme.colors.textMuted, marginTop: 2 },
  scroll: { paddingHorizontal: 12, paddingBottom: 96 },
  grid: { backgroundColor: theme.colors.surface, borderRadius: 12, borderWidth: 1, borderColor: theme.colors.border, overflow: 'hidden' },
  gridRow: { flexDirection: 'row' },
  headerCell: { backgroundColor: theme.colors.primaryLight, borderBottomWidth: 1, borderBottomColor: theme.colors.border, paddingVertical: 8 },
  hourLabelCell: {
    height: HOUR_HEIGHT,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 2,
    borderRightWidth: 1,
    borderRightColor: theme.colors.border,
  },
  timeText: { fontSize: 11, color: theme.colors.textMuted, fontWeight: '500' },
  hourSlot: {
    height: HOUR_HEIGHT,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  // ---------- Day view ----------
  dayGrid: { backgroundColor: theme.colors.surface, borderRadius: 12, borderWidth: 1, borderColor: theme.colors.border, overflow: 'hidden' },
  dayGridHeader: { flexDirection: 'row', backgroundColor: theme.colors.primaryLight, borderBottomWidth: 1, borderBottomColor: theme.colors.border, paddingVertical: 10 },
  dayHeaderCol: { flex: 1, alignItems: 'center' },
  dayLessonCol: { flex: 1, position: 'relative' },
  lessonBlockDay: {
    position: 'absolute',
    left: 4,
    right: 4,
    backgroundColor: theme.colors.primary,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    overflow: 'hidden',
    // Keep lesson blocks above the hour grid lines so taps always land on them.
    zIndex: 2,
    elevation: 2,
  },
  navQuickBtn: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: 'rgba(0,0,0,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 3,
    elevation: 3,
  },
  navQuickBtnWeek: {
    position: 'absolute',
    top: 2,
    right: 2,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 3,
    elevation: 3,
  },
  lessonBlockTimeBig: { color: '#fff', fontSize: 13, fontWeight: '700' },
  lessonBlockNameFull: { color: '#fff', fontSize: 15, fontWeight: '700', marginTop: 2 },
  lessonBlockTopic: { color: 'rgba(255,255,255,0.85)', fontSize: 12, marginTop: 2 },
  // ---------- Week view ----------
  dayHeaderCellWeek: {
    width: CELL_W,
    alignItems: 'center',
    paddingVertical: 8,
    borderRightWidth: 1,
    borderRightColor: theme.colors.border,
  },
  weekDayCol: {
    width: CELL_W,
    borderRightWidth: 1,
    borderRightColor: theme.colors.border,
    position: 'relative',
  },
  lessonBlockWeek: {
    position: 'absolute',
    left: 2,
    right: 2,
    backgroundColor: theme.colors.primary,
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 4,
    overflow: 'hidden',
  },
  lessonBlockNameWeek: { color: '#fff', fontSize: 11, fontWeight: '700', marginTop: 2 },
  lessonBlockWarn: { backgroundColor: theme.colors.faultDriving },
  // Unavailability bands — diagonal stripes & grey background
  unavailBand: {
    position: 'absolute',
    left: 4,
    right: 4,
    backgroundColor: 'rgba(148,163,184,0.25)',
    borderLeftWidth: 4,
    borderLeftColor: '#94A3B8',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    justifyContent: 'center',
    zIndex: 0,
  },
  unavailBandText: { fontSize: 11, fontWeight: '700', color: '#475569' },
  unavailBandWeek: {
    position: 'absolute',
    left: 2,
    right: 2,
    backgroundColor: 'rgba(148,163,184,0.30)',
    borderLeftWidth: 3,
    borderLeftColor: '#94A3B8',
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 0,
  },
  unavailBandTextWeek: { fontSize: 10, color: '#475569' },
  // Recurrence section in the Add Lesson sheet
  recurRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 6,
    marginTop: 4,
  },
  recurHint: { fontSize: 11, color: theme.colors.textMuted, marginTop: 2, lineHeight: 16 },
  recurWeeksBlock: { marginTop: 4 },
  weekChipsRow: { flexDirection: 'row', gap: 6, marginTop: 2 },
  weekChip: {
    paddingHorizontal: 12, paddingVertical: 8, borderRadius: 14,
    borderWidth: 1, borderColor: theme.colors.border, backgroundColor: theme.colors.background,
  },
  weekChipActive: { backgroundColor: theme.colors.primary, borderColor: theme.colors.primary },
  weekChipText: { fontSize: 13, fontWeight: '700', color: theme.colors.text },
  weekChipTextActive: { color: '#fff' },
  // Greyed-out + strikethrough state for Cancelled lessons. Kept on the diary
  // (rather than filtered out) so instructors can see what was originally booked.
  lessonBlockCancelled: {
    backgroundColor: '#E5E7EB',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    opacity: 0.85,
  },
  lessonTextCancelled: {
    color: '#6B7280',
    textDecorationLine: 'line-through',
    textDecorationStyle: 'solid',
  },
  cancelledTag: {
    position: 'absolute',
    top: 4,
    right: 6,
    backgroundColor: '#9CA3AF',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  cancelledTagText: { color: '#fff', fontSize: 9, fontWeight: '800', letterSpacing: 0.4 },
  warnDot: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: theme.colors.faultSerious,
    alignItems: 'center',
    justifyContent: 'center',
  },
  // Test-day and paid indicators live in the top-left / bottom-left corners
  // deliberately — the top-right is already used by the nav button, the
  // gap-warning dot, and the cancelled tag, and those aren't all mutually
  // exclusive with these two.
  testDayBadge: {
    position: 'absolute', top: 4, left: 4,
    width: 16, height: 16, borderRadius: 8,
    backgroundColor: theme.colors.accent,
    alignItems: 'center', justifyContent: 'center',
  },
  testDayBadgeWeek: {
    position: 'absolute', top: 2, left: 2,
    width: 13, height: 13, borderRadius: 7,
    backgroundColor: theme.colors.accent,
    alignItems: 'center', justifyContent: 'center',
  },
  paidBadge: {
    position: 'absolute', bottom: 4, left: 4,
    width: 16, height: 16, borderRadius: 8,
    backgroundColor: theme.colors.success,
    alignItems: 'center', justifyContent: 'center',
  },
  paidBadgeWeek: {
    position: 'absolute', bottom: 2, left: 2,
    width: 13, height: 13, borderRadius: 7,
    backgroundColor: theme.colors.success,
    alignItems: 'center', justifyContent: 'center',
  },
  dayName: { fontWeight: '600', color: theme.colors.text, fontSize: 12 },
  dayNum: { fontSize: 16, fontWeight: '700', color: theme.colors.primary },
  // ---------- Shared / Form ----------
  travelInfoBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: theme.colors.primaryLight,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginTop: -6,
    marginBottom: 12,
  },
  travelInfoText: { color: theme.colors.primary, fontSize: 12, fontWeight: '600', flex: 1 },
  lessonBlockTime: { color: '#fff', fontSize: 10, fontWeight: '600' },
  label: { ...theme.font.caption, fontWeight: '600', marginBottom: 6, color: theme.colors.text },
  input: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.md,
    paddingHorizontal: 14,
    height: 48,
    marginBottom: 12,
    backgroundColor: theme.colors.background,
  },
  chip: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: 999, borderWidth: 1, borderColor: theme.colors.border, marginRight: 8 },
  chipActive: { backgroundColor: theme.colors.primary, borderColor: theme.colors.primary },
  chipText: { fontSize: 14, color: theme.colors.text },
  chipTextActive: { color: '#fff', fontWeight: '600' },
  submitBtn: { backgroundColor: theme.colors.primary, height: 52, borderRadius: theme.radius.md, alignItems: 'center', justifyContent: 'center', marginTop: 8 },
  submitBtnText: { color: '#fff', fontSize: 16, fontWeight: '700' },
  detailName: { fontSize: 20, fontWeight: '700', color: theme.colors.text },
  detailTopic: { fontSize: 15, color: theme.colors.textMuted },
  notes: { fontSize: 14, color: theme.colors.text, lineHeight: 20 },
  faultsRow: { flexDirection: 'row', gap: 10 },
  faultCard: { flex: 1, borderRadius: 12, borderWidth: 2, padding: 12, alignItems: 'center' },
  faultValue: { fontSize: 22, fontWeight: '700' },
  faultLabel: { fontSize: 12, color: theme.colors.textMuted },

  // ---- Month view ----
  monthGrid: { paddingHorizontal: 8, paddingBottom: 16 },
  monthHeaderRow: { flexDirection: 'row', marginBottom: 4 },
  monthHeaderCell: { flex: 1, alignItems: 'center', paddingVertical: 6 },
  monthHeaderText: { fontSize: 12, fontWeight: '600', color: theme.colors.textMuted },
  monthRow: { flexDirection: 'row', minHeight: 84 },
  monthCell: {
    flex: 1, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.colors.border,
    padding: 4, alignItems: 'stretch',
  },
  monthDateBadge: { width: 22, height: 22, borderRadius: 11, alignItems: 'center', justifyContent: 'center' },
  monthDateBadgeToday: { backgroundColor: theme.colors.primary },
  monthDateText: { fontSize: 12, fontWeight: '600', color: theme.colors.text },
  monthDateTextDim: { color: theme.colors.border },
  monthDateTextToday: { color: '#fff' },
  monthLessonList: { marginTop: 2, gap: 2 },
  monthLessonChip: {
    backgroundColor: theme.colors.lockedBg, borderRadius: 4,
    paddingHorizontal: 4, paddingVertical: 2,
  },
  monthLessonChipText: { fontSize: 10, color: theme.colors.text },
  monthMoreText: { fontSize: 10, color: theme.colors.textMuted, fontWeight: '600' },

  // ---- Lesson type legend ----
  legendWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, paddingHorizontal: 12, paddingVertical: 8, backgroundColor: theme.colors.background },
  legendItem: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  legendDot: { width: 9, height: 9, borderRadius: 4.5 },
  legendText: { fontSize: 11, color: theme.colors.textMuted },
  hint: { fontSize: 12, color: theme.colors.textMuted, marginTop: 4, marginBottom: 8 },

  // ---- Clash confirmation modal ----
  clashBackdrop: { flex: 1, backgroundColor: 'rgba(15,23,42,0.6)', alignItems: 'center', justifyContent: 'center', padding: 24 },
  clashCard: { width: '100%', maxWidth: 380, backgroundColor: '#fff', borderRadius: 20, padding: 20, alignItems: 'center' },
  clashIconWrap: { width: 52, height: 52, borderRadius: 26, backgroundColor: theme.colors.danger, alignItems: 'center', justifyContent: 'center', marginBottom: 12 },
  clashTitle: { fontSize: 17, fontWeight: '800', color: theme.colors.text, textAlign: 'center' },
  clashLine: { fontSize: 13.5, color: theme.colors.text, marginTop: 10, lineHeight: 19 },
  clashHint: { fontSize: 12.5, color: theme.colors.textMuted, textAlign: 'center', marginTop: 14, lineHeight: 17.5 },
  clashCancelBtn: { flex: 1, minHeight: 48, borderRadius: 13, borderWidth: 1, borderColor: theme.colors.border, alignItems: 'center', justifyContent: 'center' },
  clashCancelBtnText: { fontSize: 14.5, fontWeight: '700', color: theme.colors.textMuted },
  clashConfirmBtn: { flex: 1, minHeight: 48, borderRadius: 13, backgroundColor: theme.colors.danger, alignItems: 'center', justifyContent: 'center' },
  clashConfirmBtnText: { fontSize: 14.5, fontWeight: '700', color: '#fff' },
});
