-- ============================================================================
-- Migration 049 — Gift vouchers ("Drive Vouchers")
-- ============================================================================
-- An instructor or school issues a branded PDF gift voucher for a number of
-- prepaid driving hours. This table is the record of each one, so a code is
-- unique, can be looked up, and can be marked redeemed (or cancelled) so it
-- isn't used twice.
--
-- Simple first version (agreed with Grant, 30 Sept 2026): redeeming is manual.
-- When the recipient books, the instructor adds the hours to the student's
-- wallet by hand and marks the voucher redeemed here. The voucher is hours
-- only, with no price and no payment recording.
--
--   - The code is generated by the database (never chosen by the client), in a
--     readable alphabet with no 0/O/1/I, formatted XXXX-XXXX-XXXX.
--   - "Expired" is not stored: a voucher is expired when it is still 'active'
--     and its expires_at date has passed, so it can't drift out of date.
--   - Row level security: an instructor sees and manages only their own
--     vouchers, and a school owner sees the school's. Inserts must name the
--     caller's own instructor and school.
--   - Paid plans only is enforced in the app (as with the other paid screens),
--     not here.
--
-- Idempotent: safe to re-run.
-- ============================================================================

create table if not exists public.gift_vouchers (
    id              uuid primary key default gen_random_uuid(),
    school_id       uuid not null references public.driving_schools(id) on delete cascade,
    instructor_id   uuid not null references public.instructors(id) on delete cascade,
    code            text not null unique,
    hours           numeric(5,2) not null check (hours > 0 and hours <= 100),
    recipient_name  text check (recipient_name is null or char_length(recipient_name) <= 80),
    message         text check (message is null or char_length(message) <= 300),
    issued_at       timestamptz not null default now(),
    expires_at      date not null,
    status          text not null default 'active' check (status in ('active', 'redeemed', 'cancelled')),
    redeemed_at     timestamptz,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),
    constraint gift_vouchers_expiry_after_issue check (expires_at >= (issued_at at time zone 'utc')::date)
);

create index if not exists idx_gift_vouchers_instructor on public.gift_vouchers(instructor_id, issued_at desc);
create index if not exists idx_gift_vouchers_school on public.gift_vouchers(school_id);

-- ---------------------------------------------------------------------------
-- Code generation: XXXX-XXXX-XXXX from an unambiguous alphabet, retried until
-- unused. SECURITY DEFINER so the uniqueness check sees every voucher, not just
-- the caller's rows; it is a trigger function, so EXECUTE is revoked (see 044).
-- ---------------------------------------------------------------------------
create or replace function public.gift_voucher_set_code()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    alphabet constant text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
    candidate text;
    tries int := 0;
begin
    if new.code is not null and new.code <> '' then
        return new;
    end if;
    loop
        candidate := (
            select string_agg(substr(alphabet, 1 + floor(random() * length(alphabet))::int, 1), '')
              from generate_series(1, 12)
        );
        candidate := substr(candidate, 1, 4) || '-' || substr(candidate, 5, 4) || '-' || substr(candidate, 9, 4);
        exit when not exists (select 1 from public.gift_vouchers where code = candidate);
        tries := tries + 1;
        if tries > 20 then
            raise exception 'Could not generate a unique voucher code';
        end if;
    end loop;
    new.code := candidate;
    return new;
end;
$$;

revoke all on function public.gift_voucher_set_code() from public, anon, authenticated;

drop trigger if exists trg_gift_vouchers_set_code on public.gift_vouchers;
create trigger trg_gift_vouchers_set_code
    before insert on public.gift_vouchers
    for each row execute function public.gift_voucher_set_code();

drop trigger if exists trg_gift_vouchers_updated_at on public.gift_vouchers;
create trigger trg_gift_vouchers_updated_at
    before update on public.gift_vouchers
    for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------
alter table public.gift_vouchers enable row level security;

drop policy if exists gv_instructor_all on public.gift_vouchers;
create policy gv_instructor_all on public.gift_vouchers
    for all
    using (instructor_id = public.current_user_instructor_id())
    with check (
        instructor_id = public.current_user_instructor_id()
        and school_id = public.current_user_instructor_school_id()
    );

drop policy if exists gv_owner_all on public.gift_vouchers;
create policy gv_owner_all on public.gift_vouchers
    for all
    using (public.is_school_owner(school_id))
    with check (public.is_school_owner(school_id));

comment on table public.gift_vouchers is
    'Issued gift vouchers (prepaid driving hours). Redeemed by hand: the instructor adds the hours to the '
    'student''s wallet and marks the voucher redeemed here. "Expired" is derived from expires_at, not stored.';

-- ============================================================================
-- DONE.
-- ============================================================================
